/**
 * Recall module — high-level query interface for the Bank memory subsystem.
 *
 * Wraps BankIndexStore with convenience methods for the agent tool and CLI.
 * Handles opening/closing the store, running ingest if stale, and formatting
 * results for the LLM context.
 */

import fs from "node:fs/promises";
import path from "node:path";
import { BankIndexStore } from "./index-store.js";
import { ingestRetainFacts } from "./retain-ingest.js";
import type { BankStatus, FactEntry, OpinionEntry, RecallQuery, RecallResult } from "./types.js";

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export type RecallOptions = {
  /** Agent workspace directory (e.g. ~/.openclaw/workspace). */
  workspaceDir: string;
  /** Auto-ingest daily logs before querying (default true). */
  autoIngest?: boolean;
};

/**
 * Open a recall session — ingests any new retain facts and returns a
 * query handle.  Caller must call `close()` when done.
 */
export async function openRecall(opts: RecallOptions): Promise<RecallSession> {
  const store = BankIndexStore.open(opts.workspaceDir);

  // Auto-ingest if requested (default: yes)
  if (opts.autoIngest !== false) {
    const lastIngest = store.getMeta("last_ingest");
    const staleMs = 5 * 60 * 1000; // re-ingest if older than 5 minutes
    const lastTs = lastIngest ? parseInt(lastIngest, 10) : 0;

    if (Date.now() - lastTs > staleMs) {
      await ingestRetainFacts(opts.workspaceDir, store);
    }
  }

  return new RecallSession(store, opts.workspaceDir);
}

// ---------------------------------------------------------------------------
// RecallSession
// ---------------------------------------------------------------------------

export class RecallSession {
  private readonly store: BankIndexStore;
  private readonly workspaceDir: string;

  constructor(store: BankIndexStore, workspaceDir: string) {
    this.store = store;
    this.workspaceDir = workspaceDir;
  }

  /** Run a recall query. */
  recall(query: RecallQuery): RecallResult[] {
    return this.store.recall(query);
  }

  /** Get bank status. */
  status(): BankStatus {
    return this.store.status();
  }

  /** Force re-ingest all daily logs. */
  async ingest(options?: { force?: boolean; since?: string }): Promise<{
    filesScanned: number;
    filesChanged: number;
    factsUpserted: number;
    factsRemoved: number;
    durationMs: number;
  }> {
    return ingestRetainFacts(this.workspaceDir, this.store, options);
  }

  /** Rebuild the index from scratch. */
  async rebuild(): Promise<void> {
    this.store.rebuild();
    await ingestRetainFacts(this.workspaceDir, this.store, { force: true });
  }

  /** List all known entities. */
  listEntities(): string[] {
    const rows = this.store.db
      .prepare("SELECT DISTINCT entity FROM entity_facts ORDER BY entity")
      .all() as Array<{ entity: string }>;
    return rows.map((r) => r.entity);
  }

  /** Get all facts for a specific entity. */
  getEntityFacts(entity: string): FactEntry[] {
    const results = this.store.recall({ entities: [entity], limit: 100 });
    return results.map((r) => r.fact);
  }

  /**
   * Read an entity page (generated by Reflect) if it exists.
   * Returns the Markdown content or null.
   */
  async getEntityPage(entity: string): Promise<string | null> {
    const slug = entity
      .toLowerCase()
      .replace(/[^a-z0-9_-]/g, "-")
      .replace(/-+/g, "-")
      .replace(/^-|-$/g, "");
    const pagePath = path.join(this.workspaceDir, "memory", "entities", `${slug}.md`);
    try {
      return await fs.readFile(pagePath, "utf-8");
    } catch {
      return null;
    }
  }

  /**
   * Get enriched opinion data for an entity (includes supporting/contradicting counts).
   */
  getEntityOpinions(entity: string): OpinionEntry[] {
    return this.store.listOpinions(entity);
  }

  /** Close the store. */
  close(): void {
    this.store.close();
  }
}

// ---------------------------------------------------------------------------
// Result formatting (for LLM context injection)
// ---------------------------------------------------------------------------

/**
 * Format recall results into a text block suitable for LLM context.
 *
 * When `opinions` is provided, opinion facts are enriched with
 * supporting/contradicting evidence counts from the Reflect pipeline.
 */
export function formatRecallResults(results: RecallResult[], opinions?: OpinionEntry[]): string {
  if (results.length === 0) {
    return "No matching facts found in memory bank.";
  }

  // Build opinion lookup for enrichment
  const opinionMap = new Map<string, OpinionEntry>();
  if (opinions) {
    for (const op of opinions) {
      opinionMap.set(op.id, op);
    }
  }

  const lines: string[] = [];
  for (const { fact } of results) {
    const prefix = kindEmoji(fact.kind);
    const dateTag = fact.sourceDate ? ` [${fact.sourceDate}]` : "";
    const entityTag = fact.entities.length > 0 ? ` @${fact.entities.join(" @")}` : "";

    // Enrich opinions with Reflect data
    let confidenceTag = "";
    if (fact.kind === "opinion") {
      const op = opinionMap.get(fact.id);
      if (op) {
        const supports = op.supportingFacts.length;
        const contradicts = op.contradictingFacts.length;
        confidenceTag = ` (confidence: ${(op.confidence * 100).toFixed(0)}%, +${supports}/-${contradicts} evidence)`;
      } else if (fact.confidence !== undefined) {
        confidenceTag = ` (confidence: ${(fact.confidence * 100).toFixed(0)}%)`;
      }
    }

    const citation = `${fact.sourceFile}#L${fact.sourceLine}`;

    lines.push(`${prefix}${entityTag}${dateTag}${confidenceTag}: ${fact.content}`);
    lines.push(`  ↳ ${citation}`);
  }

  return lines.join("\n");
}

function kindEmoji(kind: FactEntry["kind"]): string {
  switch (kind) {
    case "world":
      return "🌍";
    case "experience":
      return "📝";
    case "opinion":
      return "💭";
    case "summary":
      return "📋";
  }
}
